# Generated by Django 5.0.2 on 2025-06-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedimage',
            options={},
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='category',
            field=models.CharField(choices=[('Image1', 'Image 1'), ('Image2', 'Image 2'), ('Image3', 'Image 3')], max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to='gallery/uploadimage/'),
        ),
    ]
