# Generated by Django 5.0.2 on 2024-08-24 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone number must be 10 digits', regex='^\\d{10}$')]),
        ),
    ]
