# Generated by Django 5.0.2 on 2024-11-15 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='submitted_time',
        ),
    ]
